/*

 BRICK_PARTICLE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char brick_particle[] =
{
  0x00,0x70,0xF0,0x88,0x98,0xE8,0x88,0xF8,
  0x70,0x70,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x60,0xE0,0x90,0x90,0xF0,0x60,0x60,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of BRICK_PARTICLE.C */
