/*

 MRWHOSITLETTERS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mrwhositletters_h_INCLUDE
#define __mrwhositletters_h_INCLUDE

#include <gb/gb.h>
#include <gb/metasprites.h>

/* Bank of tiles. */
#define mrwhositBank 0
/* Start of tile array. */
extern const unsigned char mrwhosit[];
extern const metasprite_t mrwhosit_sprite[];

#endif

/* End of MRWHOSITLETTERS.H */
