/*

 PARTLY_BROKEN_BRICKS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char partly_broken_bricks[] =
{
  0x00,0x00,0xFF,0xFF,0x5B,0xE4,0xDD,0x32,
  0xBB,0xFF,0x48,0xFF,0xFF,0xFF,0xFF,0xFF,
  0xFF,0xFF,0xBD,0x6E,0xCB,0x34,0x14,0xFF,
  0xFB,0x44,0x64,0xFF,0x89,0xFF,0xFF,0xFF
};

/* End of PARTLY_BROKEN_BRICKS.C */
