/*

 PLANTERBOX.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include <gb/gb.h>
#include <gb/metasprites.h>

/* Start of tile array. */
const unsigned char planter_box[] =
{
  0xFF,0xFF,0x7F,0x80,0x80,0xFF,0x40,0x7F,
  0x7F,0x7F,0x00,0x3F,0x00,0x00,0x00,0x00
};

const metasprite_t planter[] = {
  METASPR_ITEM(0,0,39,0), METASPR_ITEM(0,8,3,0b00100000), METASPR_TERM
};

/* End of PLANTERBOX.C */
