/*

 PLAYERSPRITES_CINEMATIC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

**/

/** Start of tile array. **/
extern const unsigned char playerSprite_extra[];

extern const metasprite_t key_left_0[];
extern const metasprite_t key_left_1[];
extern const metasprite_t key_right_0[];
extern const metasprite_t key_right_1[];
extern const metasprite_t pull_0[];
extern const metasprite_t pull_1[];
extern const metasprite_t fallen[];
extern const metasprite_t look_up[];

/** End of PLAYERSPRITES_CINEMATIC.H **/