/*

 THOUGHT_BUBBLE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 16 to 31

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Thought_bubble_h_INCLUDE
#define __Thought_bubble_h_INCLUDE

/* Bank of tiles. */
//#define Thought_bubbleBank 0
/* Start of tile array. */
extern const unsigned char thought_bubble[];

extern const metasprite_t bubble_key[];
extern const metasprite_t bubble_empty[];
extern const metasprite_t bubble_qmark[];
extern const metasprite_t button_1[];
extern const metasprite_t button_2[];

#endif

/* End of THOUGHT_BUBBLE.H */
